# Generated by Django 3.2.4 on 2021-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='')),
                ('TTS_No', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Designation', models.CharField(max_length=100)),
                ('Batch', models.DateField()),
                ('Branch', models.IntegerField(choices=[(1, 'CSE'), (2, 'Mechanical'), (3, 'Electronic'), (4, 'Electrical'), (5, 'Civil'), (6, 'BBA'), (7, 'MBA')])),
                ('Age', models.IntegerField()),
                ('Gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Prefer Not To Say')])),
                ('Prev_Company', models.CharField(max_length=100)),
                ('Prev_Exp_Year', models.IntegerField()),
                ('Date_of_Joining', models.DateField()),
                ('Date_of_Birth', models.DateField()),
            ],
        ),
    ]
