# Generated by Django 3.2.4 on 2021-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('Mech', 'Mechanical'), ('Electronic', 'Electronic'), ('Electrical', 'Electrical'), ('Civil', 'Civil'), ('BBA', 'BBA'), ('MBA', 'MBA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Not To Say', 'Prefer Not To Say')], max_length=100),
        ),
    ]
